---
#@ load("funcs.lib.yml", "slack_hook")
#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

#!  JOBS

jobs:
  - name: set-pipeline
    plan:
      - get: src
        resource: pr
        trigger: true
      - get: pipeline-tasks
      - get: general-task
      - task: init
        image: general-task
        file: pipeline-tasks/tasks/init.yml
        params:
          PIPELINE_YML: src/ci/pipeline-dev.yml
      - set_pipeline: cf-build-tasks
        file: compiled/set-pipeline.yml
        instance_vars:
          deploy-env: ((deploy-env))

  - name: test
    plan:
      - get: src
        resource: pr
        trigger: true
        passed: [set-pipeline]
      - put: src
        resource: pr
        params:
          path: src
          status: pending
          base_context: concourse
          context: test-cf-build-tasks
      - get: python
      - task: common-test
        file: src/ci/partials/common-test.yml
        image: python
        on_success:
          put: src
          resource: pr
          params:
            path: src
            status: success
            base_context: concourse
            context: test-cf-build-tasks
        on_failure:
          put: src
          resource: pr
          params:
            path: src
            status: failure
            base_context: concourse
            context: test-cf-build-tasks

  - name: deploy-((deploy-env))
    plan:
      - get: src
        resource: pr
        trigger: true
        passed: [set-pipeline]
      - put: src
        resource: pr
        params:
          path: src
          status: pending
          base_context: concourse
          context: deploy-cf-build-tasks
      - get: general-task
      - get: oci-build-task
      - task: ls-tasks
        file: src/ci/partials/ls-tasks.yml
        image: general-task
      - load_var: build-tasks
        file: src/build-tasks.json
      - across:
          - var: build-task
            values: ((.:build-tasks))
            max_in_flight: 20
        do:
          - task: build
            privileged: true
            image: oci-build-task
            file: src/ci/partials/build.yml
            params:
              BUILD_ARG_TASK_FOLDER: tasks/((.:build-task))
              BUILD_ARGS_FILE: tasks/((.:build-task))/.env
              BUILDKIT_SECRETTEXT_UA_TOKEN: ((ua-token))
              DOCKERFILE: Dockerfile
          - task: tag-list
            file: src/ci/partials/tag-list.yml
            image: general-task
            params:
              TAG: ((.:build-task))-((deploy-env))
          - put: image-repository
            params:
              image: image/image.tar
              additional_tags: src/tag-list.txt
          - task: deploy
            file: src/ci/partials/deploy.yml
            image: general-task
            params:
              _: #@ template.replace(data.values.env_cf_build_tasks)
              CF_APP_NAME: pages-((.:build-task))-task-((deploy-env))
              CF_MANIFEST: .cloudgov/manifest.yml
              CF_VARS_FILE: .cloudgov/vars/pages-((deploy-env)).yml
              IMAGE_REPOSITORY: ../image-repository/repository
              IMAGE_TAG: ((.:build-task))-((deploy-env))
              CF_DOCKER_USERNAME: ((ecr-aws-key))
              CF_DOCKER_PASSWORD: ((ecr-aws-secret))
            on_failure: #@ slack_hook("failure", "((.:build-task)) deployment")
            on_success: #@ slack_hook("success", "((.:build-task)) deployment")
        on_success:
          put: src
          resource: pr
          params:
            path: src
            status: success
            base_context: concourse
            context: deploy-cf-build-tasks
        on_failure:
          put: src
          resource: pr
          params:
            path: src
            status: failure
            base_context: concourse
            context: deploy-cf-build-tasks

#!  RESOURCES

resources:
  - name: pr
    type: pull-request
    check_every: 1m
    source:
      repository: cloud-gov/pages-cf-build-tasks
      access_token: ((gh-access-token))
      base_branch: main
      disable_forks: true
      ignore_drafts: false

  - name: image-repository
    type: registry-image
    source:
      aws_access_key_id: ((ecr-aws-key))
      aws_secret_access_key: ((ecr-aws-secret))
      repository: pages-cf-build-tasks
      aws_region: us-gov-west-1
      tag_regex: "*-((deploy-env))"

  - name: slack
  - name: general-task
  - name: pipeline-tasks
  - name: python
  - name: oci-build-task

#! RESOURCE TYPES

resource_types:
  - name: slack-notification
  - name: pull-request
  - name: registry-image
  - name: git
